server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

graphql:
  servlet:
    mapping: /graphql/*
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        path: /subscriptions

graphiql:
  mapping: /graphiql
  enabled: true
  pageTitle: GraphiQL


---
# development profile
h2:
  console:
    path: /h2
    enabled: true
